#!/bin/bash

SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
have_real=$(type -p realpath)
[ "${have_real}" ] && SCRIPT_PATH="$(realpath $SCRIPT_PATH)"
TOP=$(dirname "${SCRIPT_PATH}")

cd "${TOP}"

have_bundle=$(type -p bundle)
if [ "${have_bundle}" ]; then
  bundle exec jekyll clean
else
  rm -rf _site .sass-cache .jekyll-cache
  rm -f .jekyll-metadata .DS_Store
fi
